import '../entities/news_entity.dart';
import '../entities/suggestion_entity.dart';

/// Repository interface for AI operations
abstract class AIRepository {
  /// Vulgarize a news article for beginners using AI
  ///
  /// Takes a NewsEntity and returns it with vulgarized content added
  /// Caches the vulgarized content with 24h TTL
  Future<NewsEntity> vulgarizeArticle(NewsEntity news);

  /// Get investment suggestions based on recent news
  ///
  /// Returns 2-3 investment suggestions generated by AI
  /// Suggestions are adapted for European market (PEA eligible)
  /// Cached for 24h
  Future<List<SuggestionEntity>> getSuggestions();
}
